FROM php:7.3-apache

# Updates package sources list
RUN apt update

# Install packages
RUN docker-php-ext-install mysqli pdo pdo_mysql && docker-php-ext-enable mysqli pdo pdo_mysql

# Copy challenge files to default document root
COPY ./html /var/www/html
COPY flag /flag_level1

# Set up permissions for owner
RUN chown -R root:www-data /var/www/html
RUN chmod 750 /var/www/html
RUN find . -type f -exec chmod 640 {} \;
RUN find . -type d -exec chmod 750 {} \;

# Add write permission for upload file
RUN chmod g+w /var/www/html/upload/

# Add sticky bit to prevent delete files
RUN chmod +t -R /var/www/html/

